top_modules:
    - fastqc:
        name: 'FastQC (sickle filtered)'
        info: 'This section of the report shows FastQC results after sickle filtering.'
        target: ''
        path_filters:
            - '*_qual_filt_fastqc.zip'
    - fastqc:
        name: 'FastQC (adapter trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*_trans_trim_fastqc.zip'
    - cutadapt:
        name: 'Cutadapt'
        info: 'This sectino of the report shows cutadapt log reports'
        target: ''
        path_filters:
            - '*_cutadapt.log'
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*_fastqc.zip'

# Cleaning up sample names
extra_fn_clean_exts:
    - '_trans_trim' # cutadapt outputs
    - '_qual_filt' # sickle outputs

# Get rid of that pesky 001 in some of the samples after R1
extra_fn_clean_trim:
    - '001'
